name: Create PR
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 * * * *'
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Changes
        run: |
          echo "foo" >> README.md
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{secrets.PAT}}
          branch-suffix: random
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          running-workflow-name: 'create-pr'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 240
      - name: Close Pull Request
        run: gh pr close "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
